[package]
name = "maratwasi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
unshare = "0.7"
hostname = { version = "0.3", features = ["set"] }
nix = "0.25"